### ISSUE TITLE
Publishing can fail if the project takes over 3 minutes to build

### ISSUE THREAD

**Issue by esplace** [JetBrains/azure-tools-for-intellij#437]
Due to the inflexible timeout, if the user attempts to publish a project that takes too long to build, the publishing will fail. This behavior makes it impossible to publish an app using the plugin. 

It would be helpful if build and upload timeouts were configurable to avoid this issue.

**Comment by sdubov** [comment]
We have two timeouts in this scope:
1. Timeout for preparing publishable package from a selected project (3 mins)
2. Timeout for pushing prepared package over a network to Azure servers (3 mins)

Preparing package step calls msbuild task. This issue is caused by timeout while preparing a package task. It looks like we need to make more flexible approach for projects that might take long time (configurable timeout or think if we can make it in a smarter way).

**Comment by kbsoftwarellc** [comment]
Do we have any known workaround for the issue? I've currently still had to open visual studio community 2019 when I want to deploy due to it timing out during build. Is there a source code I can download and change to 10 minutes or something and import in place of the current plugin?
